### ISSUE TITLE
Stable?

### ISSUE THREAD

**Issue by salihmarangoz** [salihmarangoz/system_tray_extensions#19]
Please share your reviews here. Thanks

**Comment by yuky2020** [comment]
very stable with the last update on xmg fusion15
I was trying to make your cpu usage into a music equalizer but not work as expected 

```python:
import pyaudio
import numpy as np
from matplotlib import pyplot as plt
import cv2
import matplotlib

CHUNKSIZE = 1024 # fixed chunk size

class CustomEffect:
    def __init__(self, arr):
        self.arr = arr * 0

        # parameters:
        self.cm = plt.get_cmap('jet')
        self.is_bar_plot = True

    def update(self):
        # initialize portaudio
        p = pyaudio.PyAudio()
        stream = p.open(format=pyaudio.paInt16, channels=1, rate=44100, input=True, frames_per_buffer=CHUNKSIZE)
        # do this as long as you want fresh samples
        data = stream.read(CHUNKSIZE)



        # shift to the left
        self.arr[:, :-1, :] = self.arr[:, 1:, :]

        # get cpu usage as music value i will rename it later;
        data = stream.read(CHUNKSIZE)

        cpu_usage = np.frombuffer(data, dtype=np.int16)/4000
        cpu_usage_hue = matplotlib.colors.rgb_to_hsv(self.cm(cpu_usage)[:-1])

        # compute column values
        new_column = np.zeros((self.arr.shape[0], 1))
        full_keys = int(cpu_usage * len(new_column))
        last_key_val = cpu_usage * len(new_column) - full_keys
        if self.is_bar_plot:
            new_column[len(new_column)-full_keys:] = 1.0
            if full_keys < len(new_column):
                new_column[len(new_column)-full_keys-1] = last_key_val
        else:
            if full_keys < len(new_column):
                new_column[len(new_column)-full_keys-1] = 1.0
            else:
                new_column[len(new_column)-full_keys] = 1.0

        # construct hsv img
        hue = np.ones(new_column.shape) * 360 * cpu_usage_hue[0]
        saturation = np.ones(new_column.shape) * cpu_usage_hue[1]
        value = new_column

        # hsv to rgb
        hsv = np.moveaxis(np.stack([hue, saturation, value]), 0, 2)
        hsv = np.asarray(hsv, dtype=np.float32)
        self.arr[:, -1, :] = cv2.cvtColor(hsv, cv2.COLOR_HSV2RGB).squeeze(1)

        # close stream
        stream.stop_stream()
        stream.close()
        p.terminate()


        return self.arr

    def get_fps(self):
        return 5

    def is_enabled(self):
        return True

    def on_exit(self):
        pass

**Comment by salihmarangoz** [comment]
Thanks for your answer. Good to hear that it is stable.

I have tried to make a music equalizer too, but it doesn't work out of the box and has many problems. It needs PulseAudio modules to be set and everything connected according to that but I couldn't do it. I have also tried python modules other than pyaudio but still the same.

But this is in my mind. If I can find a way I will implement it.

**Comment by salihmarangoz** [comment]
I think I am getting something with this code. I will implement it when I find some time.

```
import soundcard as sc
mics = sc.all_microphones(include_loopback=True)

for m in mics:
    if m.isloopback:
        with m.recorder(samplerate=48000) as mic:
            for _ in range(100):
                data = mic.record(numframes=1024)
                print(data)
```

**Comment by salihmarangoz** [comment]
@yuky2020 I have implemented most of it excluding processing audio to get frequency values. I don't have a background on audio so I will leave it like this for a while. You can try implementing the function: https://github.com/salihmarangoz/system_tray_extensions/blob/main/rgb_kb_custom/TODO_audio_spectrum_analyzer.py
The current code can get "what-u-hear" audio can pass it to the process_audio function. It just needs to be implemented.

**Comment by Invertisment** [comment]
I think there are too many concerns that this extension handles.

For instance I wanted to install a way to control my keyboard lights and nothing more. But it also adds Nvidia GPU notification when I unplug my cable. I think I don't need it as I wanted to have a basic keyboard menu.

Also some people may want update notification but then why not ship your own ubuntu ppa (as primarily support ubuntu/debian)?

Also I could've used something from terminal but it doesn't exist. Maybe I'll try to make my own ("borrow" from your code?) but I'm not sure. What I expect would be some kind of `systemd` service that simply applies the config when it's started. But well... current implementation works as well.

**Comment by salihmarangoz** [comment]
> I think there are too many concerns that this extension handles.
> 
> For instance I wanted to install a way to control my keyboard lights and nothing more. But it also adds Nvidia GPU notification when I unplug my cable. I think I don't need it as I wanted to have a basic keyboard menu.
> 
> Also some people may want update notification but then why not ship your own ubuntu ppa (as primarily support ubuntu/debian)?
> 
> Also I could've used something from terminal but it doesn't exist. Maybe I'll try to make my own ("borrow" from your code?) but I'm not sure. What I expect would be some kind of `systemd` service that simply applies the config when it's started. But well... current implementation works as well.

Thank you for your feedback. I am already aware of this issue. I will make STE be able to enable/disable modules. I am thinking of a settings section. I just couldn't find time to implement it. I will do this next time!

Why am I not shipping this with PPA: It would be difficult to maintain for other distributions. Also, I may add more things and new dependencies may break something. I am aware that adding more tools increases dependencies but I will find a way to make them installed dynamically. It needs more time to think about and implement. But, I don't want to put my time into this if it is not important.

For the dGPU and power indicator. You will be able to disable them in the future versions. If you want to remove them immediately, remove the related entries in the `modules/loading_order.list` for now. This will be changed in the future. Also, I added these two indicators because people usually suffer from bad battery life on laptops, and these indicators show how much power is being drawn from the battery and remind if the user forgot to switch to iGPU, or maybe there is an app keeping the dGPU awake. Keeping the dGPU awake may reduce 6hrs battery life to 2hrs or less.

I am also still thinking about how users should update this package. I just need ideas other than PPA, since people may modified the code and I don't want to overwrite these changes. I would like to see those changes as a pull request instead.

**If you have problems, ideas, etc. open an issue so we can discuss it. I just wanted more people to utilize their Linux laptops better since I am also a laptop user. I just didn't keep this project to myself :)**

**Comment by Invertisment** [comment]
I think that what you want is people putting their own plugins into some kind of `/usr/share/plugins` or `.local/share/plugins` directory. And then it would allow plugins as you want them. Then the updates won't be a problem.

**Comment by salihmarangoz** [comment]
Makes sense. I will think about it when more modules are added. So, I can find a good way to generalize plugin interfaces and put them into different folders, repositories, etc. I am still trying different ideas and comparing them with other control center software. In the most ideal case, STE will be the control center and there will be different modules with their separate installations and readme's. Thank you for you idea.

**Comment by augustoicaro** [comment]
Hey, MAG-15/Fusion 15 user here.

First of all, thanks for york work! It is everything work as expected. I had some problems with system tray submenus in elementary OS 6, but was a system problem (fix described [here](https://elementaryos.stackexchange.com/questions/17452/how-to-display-system-tray-icons-in-elementary-os-juno#comment28965_17453)).

I used it for some hours, tested all options and almost everything is pretty stable to me. 
The only thing that I more time to test is gpu use indicator. When I was in battery mode it was showing even when I was using only integrated graphics. Also when I switched in nvidia control center to use gpu as default, the icon didn't appear after reboot, even when I run `glxgears`.

**Comment by salihmarangoz** [comment]
> Hey, MAG-15/Fusion 15 user here.
> 
> First of all, thanks for york work! It is everything work as expected. I had some problems with system tray submenus in elementary OS 6, but was a system problem (fix described [here](https://elementaryos.stackexchange.com/questions/17452/how-to-display-system-tray-icons-in-elementary-os-juno#comment28965_17453)).
> 
> I used it for some hours, tested all options and almost everything is pretty stable to me. The only thing that I more time to test is gpu use indicator. When I was in battery mode it was showing even when I was using only integrated graphics. Also when I switched in nvidia control center to use gpu as default, the icon didn't appear after reboot, even when I run `glxgears`.

Thank you for your feedback. I will add your solution and report to the readme.

**Some information:** About the gpu indicator, it is just reading `/sys/module/nvidia/drivers/pci:nvidia/0000:01:00.0/power_state`. Running `nvidia-smi` may wake up the device so I solved the problem this way. If the state is `d3cold` then it is turned off, otherwise, the dGPU is on. Sometimes the dGPU may wake up just after the reboot, running some programs (for example starting chrome wakes up the dGPU but it sleeps again in a few minutes). I think some apps are running `nvidia-smi` in the background. Also, some apps like `psensor` can prevent the dGPU from sleeping because it runs the command in a loop. 

So, can you check `/sys/module/nvidia/drivers/pci:nvidia/0000:01:00.0/power_state` and run STE `start.sh` to see the outputs? If there is a problem I think I can solve it.

**Comment by augustoicaro** [comment]
Thanks for the information! I will try see why my gpu is on and try to tweak this :)

**Comment by Jinx138** [comment]
Great Work! Runs stable on my Tuxedo Stellaris 17 Gen 3 on 5.16.14-1-MANJARO.

I have a request though: Would it be very difficult to support custom modes for one more row of keys? I tried to get the LEDs on the far right (Page down, NUM-Minus, NUM-Plus, Enter) working by adding exactly one more row to the default.png which would match the keyboardlayout without success. They seem to be dark all the time, no matter what.
![IMG_20220318_151911](https://user-images.githubusercontent.com/33814877/159020878-f040aa09-20de-4dca-9423-e4b97cae7558.jpg)

**Comment by salihmarangoz** [comment]
> Great Work! Runs stable on my Tuxedo Stellaris 17 Gen 3 on 5.16.14-1-MANJARO.
> 
> I have a request though: Would it be very difficult to support custom modes for one more row of keys? I tried to get the LEDs on the far right (Page down, NUM-Minus, NUM-Plus, Enter) working by adding exactly one more row to the default.png which would match the keyboardlayout without success. They seem to be dark all the time, no matter what. ![IMG_20220318_151911](https://user-images.githubusercontent.com/33814877/159020878-f040aa09-20de-4dca-9423-e4b97cae7558.jpg)

Can you try replacing all "18" values with "19" in "modules/Ite8291r3/main.py". This should solve your problem not with only PNG but videos and effects. Did it solve your problem?

I thought about this since I noticed that ITE device supports up to 21 columns. But I didn't try it since I have a 15inch version of Stellaris. I will solve this issue in the new version better.

**Comment by Jinx138** [comment]
> 

Yes, It worked! Kudos!
