### ISSUE TITLE
How would I control the line in the front?

### ISSUE THREAD

**Issue by Invertisment** [salihmarangoz/system_tray_extensions#38]
The query gives out only one device:
```
sudo python -m ite8291r3_ctl query --devices
bus 3 addr 4 rev 0.03 product 6004:'ITE Device(8291)' manufacturer 048d:'ITE Tech. Inc.'
```
Is this correct?
Output of `lsusb -d 048d:` is the same. 
Have you tried to control the front line? 

I expect to get two devices. Maybe I installed something badly.

**Comment by salihmarangoz** [comment]
Line in the front? Could you attach some photos, maybe? So, I can get a better understanding of the problem.

**Comment by Invertisment** [comment]
Yes, the lightbar.
```
ls /sys/devices/platform/tuxedo_keyboard/leds
lightbar_animation::status  lightbar_rgb:1:status  lightbar_rgb:2:status  lightbar_rgb:3:status
```

**Comment by salihmarangoz** [comment]
Looks like most of the things are ok. Have you applied this section? https://github.com/salihmarangoz/system_tray_extensions#enable-write-permissions-for-sysclassleds

**Comment by salihmarangoz** [comment]
Try running these two commands below. Does the light change or do you get errors related to writing permissions?

```
$ echo 36 > /sys/devices/platform/tuxedo_keyboard/leds/lightbar_rgb:1:status/brightness
$ echo 0 > /sys/devices/platform/tuxedo_keyboard/leds/lightbar_rgb:1:status/brightness
```

**Comment by Invertisment** [comment]
I don't get any error.
But instead the lightbar stopped animating the rainbow and now it's green.
When I write 36 I get bleak pine-green color. When I write 0 I get something similar to aquamarine.
Well... the command does something...

But I didn't run your commands from the link and instead opened a root terminal.
I don't think this should change anything.

**Comment by salihmarangoz** [comment]
You have to apply steps mentioned in the link. Since root terminal has all permission you are able to modify leds, but STE is running with normal permissions. The mentioned section in the readme modifies permissions for leds to enable STE to access.

**Comment by Invertisment** [comment]
Alright. Thanks.
I wanted to control it from `ite8291r3_ctl` directly. I guess it's not going to work.

**Comment by salihmarangoz** [comment]
Oh... Yes, the lightbar is not connected to ite8291, it is another device. This code controls that led in this project: https://github.com/salihmarangoz/system_tray_extensions/blob/main/modules/TuxedoKeyboard/main.py 
You can also check the Tuxedo website here for the lightbar control https://www.tuxedocomputers.com/en/Infos/Help-Support/Instructions/Installation-of-keyboard-drivers-for-TUXEDO-Computers-models-with-RGB-keyboard-.tuxedo . It is described in the "Special Notes for XMG Fusion 15" section.

**Comment by Invertisment** [comment]
One of the reasons why I didn't want to use that code was that I run Manjaro. So the install script doesn't work and my first try didn't work. Some kind of PyObject (don't remember) dependency is broken and doesn't install at all. UI widget with suspend and other callbacks would've been great but it didn't compile.

**Comment by salihmarangoz** [comment]
I implemented the install script for Ubuntu/Debian-based distro's. If you can do the installation by yourself it should work. Can you port it to Manjaro?

If you can't port it, I can try porting the installer for Manjaro/Arch etc. distros in VM, so you can try it and report if it is working or not. Would you like to do it?

**Comment by salihmarangoz** [comment]
There are 3 different downloads. Which one should I port it to? XFCE, Plasma, or GNOME version?

**Comment by Invertisment** [comment]
This OS package:
`gobject-introspection-1.70.0-2-x86_64` fails to install.
(`sudo pacman -S gobject-introspection`)

And if I don't install it then I get this error:
```
running build_ext
  Package gobject-introspection-1.0 was not found in the pkg-config search path.
  Perhaps you should add the directory containing `gobject-introspection-1.0.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'gobject-introspection-1.0', required by 'virtual:world', not found
  Command '('pkg-config', '--print-errors', '--exists', 'gobject-introspection-1.0 >= 1.56.0')' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for PyGObject
Failed to build PyGObject
ERROR: Could not build wheels for PyGObject, which is required to install pyproject.toml-based projects
```
