### ISSUE TITLE
XMG Fusion 15 - Menu System Tray extension crashed when changing the lightbar

### ISSUE THREAD

**Issue by 50hoursaweek** [salihmarangoz/system_tray_extensions#56]
When I click on the Menu tray extension to change the lightbar the system tray extension crashed.
I can change the keyboard color without any issues.

System:
OS: Pop!_OS 21.04 x86_64 
Host: XMG FUSION 15 (XFU15L19) Late 2019 
Kernel: 5.13.0-7620-generic 

-- Error message when running from terminal the start.sh
[output.txt](https://github.com/salihmarangoz/system_tray_extensions/files/7604826/output.txt)

**Comment by yuky2020** [comment]
Check led class permission and if tuxedo driver are installed

**Comment by salihmarangoz** [comment]
Lightbar has a different controller compared to ite8291. So you need tuxedo-keyboard module to get it working: https://github.com/tuxedocomputers/tuxedo-keyboard

Also I have noticed `ValueError: Namespace AppIndicator3 not available` error. `gir1.2-appindicator3-0.1` debian package should be installed for it. But I am not sure about the arch package. Is it `libappindicator-gtk3`? Any ideas?

**Comment by salihmarangoz** [comment]
Can someone confirm that it works (or the new package is needed) in Arch?

**Comment by salihmarangoz** [comment]
I am closing the issue since it looks solved
