### ISSUE TITLE
How to uninstall?

### ISSUE THREAD

**Issue by Uhter** [salihmarangoz/system_tray_extensions#75]
Hi :)

I would try it on my _Tuxedo Polaris 17 AMD Gen3_ but before I would like to know what is the uninstall instruction.
I'm a newbie.

**Comment by salihmarangoz** [comment]
**First check if the project is compatible** (if you have a supported multicolor (RGB) backlit keyboard). Run `lsusb` and check if there is a line that looks like this: "Bus 003 Device 006: ID 048d:6004 Integrated Technology Express, Inc.". If you can see it then you probably have an RGB keyboard capable of controlling each individual key separately, go for the installation. If not then, it is not supported so do not install and instead check this page for controlling keyboard backlight: https://www.tuxedocomputers.com/en/Infos/Help-Support/Instructions/Installation-of-keyboard-drivers-for-TUXEDO-Computers-models-with-RGB-keyboard-.tuxedo

For uninstalling:

```bash
# Remove Desktop Entry:
$ xdg-desktop-menu uninstall ~/.system_tray_extensions/system_tray_extensions.desktop
# Remove USB Permissions:
$ sudo rm /etc/udev/rules.d/99-ste.rules
```

And lastly, manually delete ".system_tray_extensions" folder in your home directory (folder size is about ~790MB).

**Comment by Uhter** [comment]
Thanks for your complete answer. Very usefull ;)
And tx for your work!
