### ISSUE TITLE
turning off after a while

### ISSUE THREAD

**Issue by sirnicolas21** [salihmarangoz/system_tray_extensions#76]
installed fine and started working but after a while the light is turned off and i need to restart the tray
there is no output from "start.sh" when this happens and it takes random time to do so
KDE NEON 20.04 
XMG NEO 15 2021

```
$ cat /home/sirnicolas21/.system_tray_extensions/app.log
INFO:root:=== APP STARTED ===
INFO:root:State file is found: /home/sirnicolas21/.system_tray_extensions/modules/Core/../../state.json
INFO:root:Reloading state: {'mode': 'mono', 'value': [0, 0, 1.0], 'brightness': 0.5, 'toggle': True}
INFO:root:State file is found: /home/sirnicolas21/.system_tray_extensions/modules/Core/../../state.json
INFO:root:State file saved: /home/sirnicolas21/.system_tray_extensions/modules/Core/../../state.json
INFO:root:Initialized Ite8291r3
INFO:root:State file is found: /home/sirnicolas21/.system_tray_extensions/modules/Core/../../state.json
INFO:root:None
INFO:root:Error initializing module TuxedoKeyboard
INFO:root:State file is found: /home/sirnicolas21/.system_tray_extensions/modules/Core/../../state.json
INFO:root:enter power_state_check_function
INFO:root:Initialized DgpuPowerstateMonitor
INFO:root:Initialized BatteryPowerDrawMonitor
DEBUG:git.cmd:Popen(['git', 'version'], cwd=/home/sirnicolas21/.system_tray_extensions, universal_newlines=False, shell=None, istream=None)
DEBUG:git.cmd:Popen(['git', 'version'], cwd=/home/sirnicolas21/.system_tray_extensions, universal_newlines=False, shell=None, istream=None)
INFO:root:Initialized UpdateManager
DEBUG:git.cmd:Popen(['git', 'fetch', '-v', 'origin'], cwd=/home/sirnicolas21/.system_tray_extensions, universal_newlines=True, shell=None, istream=None)
DEBUG:git.cmd:Popen(['git', 'status', '-sb'], cwd=/home/sirnicolas21/.system_tray_extensions, universal_newlines=False, shell=None, istream=None)
INFO:root:UpdateManager fetch and status: ## main...origin/main
 M start.sh
INFO:root:New event: exit
INFO:root:Waiting for EventManager
ERROR:root:module_name: TuxedoKeyboard
INFO:root:Waiting for Ite8291r3
ERROR:root:None
INFO:root:Waiting for TuxedoKeyboard
INFO:root:Waiting for DgpuPowerstateMonitor
INFO:root:exit power_state_check_function
INFO:root:Waiting for BatteryPowerDrawMonitor
INFO:root:Waiting for UpdateManager
INFO:root:Waiting for Qt
WARNING:root:Qt interrupted by SIGINT

```

**Comment by salihmarangoz** [comment]
I have very similar hardware too, but well this is pretty weird. Have you installed any other apps trying to control the keyboard? It can be OpenRGB, or some power-saving utilities (e.g. TLP), etc.

**Comment by sirnicolas21** [comment]
no nothing else installed, i didn't even knew OpenRGB, checked, nothing on battery settings also that is similar, it closes off while i am using it also, not only when i am away

**Comment by salihmarangoz** [comment]
Well, I think the RGB controller resource is owned by STE even without animations. Maybe dmesg and journal outputs can be useful for solving this. Also, you can check https://github.com/pobrn/ite8291r3-ctl project if it has the same problem.

**Comment by sirnicolas21** [comment]
i have no idea whats going on, i have a tail on syslog for two days now and not only it did not switch off but after a reboot i released that the leds work as they are supposed to even without STE running

i had that issue for like 3 months, the leds was automatically switched off when i was logging in, thats why i installed STE
now even that problem is gone

maybe an OS update fixed it?

**Comment by salihmarangoz** [comment]
maybe... anyway the problem solved itself :)

**Comment by sirnicolas21** [comment]
well it appeared again after months of normal use
```

Jun 15 20:05:48 LaptopKDE org_kde_powerdevil[1494]: org.kde.powerdevil: Unsatisfied policies, the action has been aborted
Jun 15 20:06:33 LaptopKDE dbus-daemon[826]: [system] Activating service name='org.kde.powerdevil.backlighthelper' requested by ':1.48' (uid=1000 pid=1494 comm="/usr/lib/x86_64-linux-gnu/libexec/org_kde_powerdev" label="unconfined") (using servicehelper)
Jun 15 20:06:33 LaptopKDE dbus-daemon[826]: [system] Successfully activated service 'org.kde.powerdevil.backlighthelper'

```
i managed to fetch this from syslog, any ideas? it seems not STE related but you might have an idea on what it is
i just disabled "dim screen" from kde energy panel just in case it does something, but it will take a long time to confirm if this is it maybe.

**Comment by salihmarangoz** [comment]
This happens to me rarely (once in two months) with Ubuntu 20.04. I will reopen the issue so we can confirm it, maybe.

**Comment by sirnicolas21** [comment]
"dim screen" didn't fix it

**Comment by salihmarangoz** [comment]
> "dim screen" didn't fix it

Does it turn off while animations are running? Or are the RGB lights are static?

**Comment by sirnicolas21** [comment]
static always, i never used animations, will test now breathing from build-in

**Comment by sirnicolas21** [comment]
yes animations also stuck

**Comment by salihmarangoz** [comment]
> yes animations also stuck

I mean video or python script animations which needs frequent update of key lights.

**Comment by sirnicolas21** [comment]
ok trying aurora.mp4

**Comment by sirnicolas21** [comment]
it stopped yes, nothing in syslog

**Comment by salihmarangoz** [comment]
weird. have no idea

**Comment by sirnicolas21** [comment]
after digging into kde.powerdevil code i found those lines which 

```
    QAction *globalAction = actionCollection->addAction(QLatin1String("Increase Keyboard Brightness"));
    globalAction->setText(i18nc("@action:inmenu Global shortcut", "Increase Keyboard Brightness"));
    accel->setGlobalShortcut(globalAction, Qt::Key_KeyboardBrightnessUp);
    connect(globalAction, &QAction::triggered, this, &KeyboardBrightnessControl::increaseKeyboardBrightness);

    globalAction = actionCollection->addAction(QLatin1String("Decrease Keyboard Brightness"));
    globalAction->setText(i18nc("@action:inmenu Global shortcut", "Decrease Keyboard Brightness"));
    accel->setGlobalShortcut(globalAction, Qt::Key_KeyboardBrightnessDown);
    connect(globalAction, &QAction::triggered, this, &KeyboardBrightnessControl::decreaseKeyboardBrightness);

    globalAction = actionCollection->addAction("Toggle Keyboard Backlight");
    globalAction->setText(i18nc("@action:inmenu Global shortcut", "Toggle Keyboard Backlight"));
```
those actions exist in shortcuts
![image](https://user-images.githubusercontent.com/29731821/174274146-5dafb0b2-5aa4-4239-b3fa-abee19cc33ff.png)
all were enabled without a combination set, when i set a combination they do not work at all, i disabled them for now and its some hours passed without problems, i will monitor it for a week and come back to close the issue (which is clearly not STE related)

**Comment by sirnicolas21** [comment]
nope thats not it

**Comment by salihmarangoz** [comment]
STE tries to own the backlight device, when an error occurs STE tries it again and again. If there is an animation that requires the backlight to be updated by STE frequently and there is still this issue and STE doesn't get that it lost the device's control... Maybe a hardware problem...

**Comment by sirnicolas21** [comment]
i do not see a retry to turn the light on, it only turns it on if i re select something, like the brightness %. its not a hardware problem, windows never turns it off, i think its a weird KDE bug somewhere

**Comment by sirnicolas21** [comment]
is there anyway to disable the backlight device totally?

**Comment by salihmarangoz** [comment]
Nowadays I am playing with OpenRGB. ITE8291 is not implemented but maybe I can. The thread is here: https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/720 I will look at it when I have some time. 

By the way, ite8291-ctl detaches usb kernel driver. Maybe communicating over kernel driver is possible. I need more information and now I am reading some docs about it.

**Comment by sirnicolas21** [comment]
https://deb.tuxedocomputers.com/ubuntu/pool/main/t/tuxedo-keyboard-ite/tuxedo-keyboard-ite_0.2.3_all.deb
resolved after installing this
