### ISSUE TITLE
Feedback Pop_Os 22.04

### ISSUE THREAD

**Issue by lbonini94** [salihmarangoz/system_tray_extensions#78]
![image](https://user-images.githubusercontent.com/41344961/167763825-6a2d9448-0662-4d46-960d-3b833ef1bfbc.png)

Keyboard is fully green and lightbar is fading (rainbow)

**Comment by indika-dev** [comment]
Same here @Tuxedo OS 1 / Stellaris 15 Gen 4 (AMD) / ite8291r3-ctl works flawlessly
Even after I got the AppIndicator working, it was not clickable(nothing happened).
My personal assumption is, that you rely on PyQT(KDE) and I use Gnome.

**Comment by salihmarangoz** [comment]
this is not related to Tuxedo. Also, I am using Gnome with Ubuntu 20.04 but it is working well.

I just can't find time to fix these bugs besides my master's thesis. Sorry to hear that you are experiencing problems.

**Comment by augustoicaro** [comment]
I installed Nobara 37 with gnome this week and created a PR that fixes the problem of the tray not being clickable on gnome environments.

**Comment by salihmarangoz** [comment]
Since this problem looks like fixed I am closing it. Thank you @augustoicaro !
